services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=textile'
      - 'MYSQL_PASSWORD=cinar-1907'
      - 'MYSQL_ROOT_PASSWORD=cinar-1907'
      - 'MYSQL_USER=cinar'
    ports:
      - '3306'
